Longest word:HILLBILLIES
Longest word:GEOLOGIES
Longest word:HELLHOLES
Longest word:ILLEGIBLE
Longest word:EGGSHELLS
Longest word:BESIEGES
Longest word:EGGSHELL
Longest word:ELIGIBLE
Longest word:GLOSSIES
Longest word:HELLHOLE
